const words = [
  {en: "improve", ru: "совершенствовать"},
  {en: "wrinkles", ru: "морщины"},
  {en: "thin", ru: "худой, тонкий"},
  {en: "deep", ru: "глубокий"},
  {en: "cuts", ru: "порезы"},
  {en: "soft", ru: "мягкий, нежный"},
  {en: "smell", ru: "запах"},
  {en: "turn", ru: "поворачивать, менять"},
  {en: "calm", ru: "спокойствие"},
  {en: "try", ru: "пытаться"},
  {en: "put", ru: "класть"},
  {en: "gone", ru: "уходить"},
  {en: "broke", ru: "сломал"},
  {en: "which", ru: "который"},
  {en: "quite", ru: "довольно, достаточно"},
  {en: "possible", ru: "возможно"},
  {en: "move", ru: "переезжать, двигаться"},
  {en: "lost", ru: "потерянный"},
  {en: "mistake", ru: "ошибка"},
  {en: "better", ru: "лучше"},
  {en: "during", ru: "в течение (времени)"},
  {en: "survive", ru: "выживать"},
  {en: "close", ru: "закрытый, близкий"},
  {en: "hear", ru: "слышать"},
  {en: "such", ru: "такой"},
  {en: "difficult", ru: "трудный"},
  {en: "happens", ru: "случается, происходит"},
  {en: "sure", ru: "уверен"},
  {en: "change", ru: "изменять"},
  {en: "opinion", ru: "мнение"},
  {en: "just", ru: "только"},
  {en: "careful", ru: "осторожный, внимательный"},
  {en: "quickly", ru: "быстро"},
  {en: "whole", ru: "весь, целый"},
  {en: "keep", ru: "держать, хранить"},
  {en: "empty", ru: "пустой"},
  {en: "different", ru: "различный, другой"},
  {en: "become", ru: "становиться"},
  {en: "wish", ru: "желание, пожелание"},
  {en: "tired", ru: "уставший"},
  {en: "let", ru: "позволять, разрешать"},
  {en: "through", ru: "через"},
  {en: "here", ru: "здесь, в этот момент"},
  {en: "especially", ru: "особенно, главным образом"},
  {en: "explain", ru: "объяснять"},
  {en: "meaning", ru: "значение, смысл"},
  {en: "shout", ru: "крик"},
  {en: "enjoy", ru: "наслаждаться"},
  {en: "prepare", ru: "подготавливать"},
  {en: "brings", ru: "приносит"},
  {en: "begin", ru: "начинать"},
  {en: "expand", ru: "расширять"},
  {en: "catch", ru: "ловить"},
  {en: "choose", ru: "выбирать, предпочитать"},
  {en: "still", ru: "всё ещё"},
  {en: "behind", ru: "позади"},
  {en: "under", ru: "под"},
  {en: "quietly", ru: "тихо, спокойно"},
  {en: "useless", ru: "бесполезный"},
  {en: "afraid", ru: "испуганный"},
  {en: "useful", ru: "полезный"},
  {en: "owner", ru: "владелец"},
  {en: "marries", ru: "вступает в брак"},
  {en: "without", ru: "без"},
  {en: "already", ru: "уже, давно"},
  {en: "laugh", ru: "смеяться"},
  {en: "able", ru: "способный (сделать что-то)"},
  {en: "apologize", ru: "извиняться"},
  {en: "grown-up", ru: "взрослый"},
  {en: "even", ru: "даже"},
  {en: "enough", ru: "достаточно"},
  {en: "few", ru: "немного, несколько"},
  {en: "saw", ru: "видел"},
  {en: "magnificent", ru: "великолепный"},
  {en: "virgin", ru: "девственник, нетронутый"},
  {en: "beast", ru: "зверь, скотина"},
  {en: "swallow", ru: "проглатывать"},
  {en: "prey", ru: "добыча"},
  {en: "frighten", ru: "пугать"},
  {en: "require", ru: "требовать"},
  {en: "digesting", ru: "переваривать"},
  {en: "could", ru: "мог"},
  {en: "instead", ru: "взамен"},
  {en: "thus", ru: "таким образом"},
  {en: "abandon", ru: "отказываться от, покидать"},
  {en: "failure", ru: "неудача"},
  {en: "among", ru: "среди"},
  {en: "rubbed", ru: "тереть, протирать"},
  {en: "gravely", ru: "серьёзно"},
  {en: "ravishing", ru: "восхитительный"},
  {en: "except", ru: "кроме"},
  {en: "must", ru: "должен"},
  {en: "arrive", ru: "прибывать"},
  {en: "poor", ru: "бедный"},
  {en: "though", ru: "хотя"},
  {en: "nowhere", ru: "нигде, никуда"},
  {en: "early", ru: "рано"},
  {en: "often", ru: "часто"},
  {en: "alone", ru: "один"},
  {en: "pocket", ru: "карман"},
  {en: "hit", ru: "удар, успех"},
  {en: "obey", ru: "подчиняться"},
  {en: "plates", ru: "тарелки, блюда"},
  {en: "spoke", ru: "говорил"},
  {en: "perhaps", ru: "возможно"},
  {en: "carried", ru: "носил, переносил"},
  {en: "those", ru: "те, таких"},
  {en: "mistress", ru: "госпожа"},
  {en: "suddenly", ru: "внезапно"}
];
