const words‎ = [
  {en: "apologize", ru: "извиняться"},
  {en: "grown-up", ru: "взрослый"},
  {en: "even", ru: "даже"},
  {en: "enough", ru: "достаточно"},
  {en: "few", ru: "несколько, немного"},
  {en: "saw", ru: "видел"},
  {en: "magnificent", ru: "великолепный"},
  {en: "virgin", ru: "девственник, нетронутый"},
  {en: "beast", ru: "скотина, зверь"},
  {en: "swallow", ru: "проглатывать"},
  {en: "prey", ru: "добыча"},
  {en: "frighten", ru: "пугать"},
  {en: "require", ru: "требовать"},
  {en: "digesting", ru: "переваривать"},
  {en: "could", ru: "мог"},
  {en: "instead", ru: "взамен"},
  {en: "thus", ru: "таким образом"},
  {en: "abandon", ru: "отказываться от, покидать"},
  {en: "failure", ru: "неудача"},
  {en: "among", ru: "среди"},
  {en: "rubbed", ru: "тереть, протирать"},
  {en: "gravely", ru: "серьёзно"},
  {en: "ravishing", ru: "восхитительный"},
  {en: "except", ru: "кроме"},
  {en: "must", ru: "должен"},
  {en: "arrive", ru: "прибывать"},
  {en: "poor", ru: "бедный"},
  {en: "though", ru: "хотя"},
  {en: "nowhere", ru: "нигде, никуда"},
  {en: "early", ru: "рано"},
  {en: "often", ru: "часто"},
  {en: "alone", ru: "один"},
  {en: "pocket", ru: "карман"},
  {en: "hit", ru: "удар, успех"},
  {en: "obey", ru: "подчиняться"},
  {en: "plates", ru: "тарелки"},
  {en: "spoke", ru: "говорил"},
  {en: "perhaps", ru: "возможно"},
  {en: "carried", ru: "носил"},
  {en: "those", ru: "те, таких"},
  {en: "mistress", ru: "госпожа"},

  {en: "excited", ru: "рад, взволнован"},
  {en: "lies", ru: "лежит / лжёт"},
  {en: "warm", ru: "тёплый"},
  {en: "each", ru: "каждый"},
  {en: "passes", ru: "проходит"},
  {en: "shine", ru: "сиять"},
  {en: "across", ru: "через"},
  {en: "proud", ru: "гордый"},
  {en: "hurt", ru: "ранить, причинять боль"},
  {en: "brave", ru: "храбрый"},
  {en: "remain", ru: "оставаться"},
  {en: "merry", ru: "весёлый"},
  {en: "silence", ru: "тишина"},
  {en: "kin", ru: "родственники"},
  {en: "tidings", ru: "весть, новости"},
  {en: "evening", ru: "вечер"},
  {en: "forget", ru: "забывать"},
  {en: "pull", ru: "тянуть"},
  {en: "forever", ru: "навсегда"},
  {en: "foolish", ru: "глупый"},
  {en: "ties", ru: "связи, узы"},
  {en: "alright", ru: "хорошо, в порядке"},
  {en: "weak", ru: "слабый"},
  {en: "hold", ru: "держать / проводить"},
  {en: "sweat", ru: "пот"},
  {en: "throw", ru: "бросать"},
  {en: "fall", ru: "падать"},
  {en: "bite", ru: "кусать"},
  {en: "carry", ru: "нести"},
  {en: "same", ru: "тот же"},
  {en: "truly", ru: "по-настоящему"},
  {en: "noon", ru: "полдень"},
  {en: "decide", ru: "решать"},
  {en: "yet", ru: "ещё, пока"},
  {en: "suddenly", ru: "внезапно"},
  {en: "decided", ru: "решила"},
  {en: "stairs", ru: "лестница"},
  {en: "follow", ru: "следовать"},
  {en: "whisper", ru: "шептать"},
  {en: "sick", ru: "недомогание"},
  {en: "tell", ru: "рассказать"},
  {en: "clothes", ru: "одежда"},
  {en: "any", ru: "любой, какой-нибудь"},
  {en: "done", ru: "сделано"},
  {en: "floor", ru: "пол"},
  {en: "vile", ru: "мерзкий"},
  {en: "pretty", ru: "симпатичный"},
  {en: "should", ru: "следует"},
  {en: "gently", ru: "мягко, нежно"},
  {en: "known", ru: "известный"},
  {en: "honest", ru: "честный"},
  {en: "tempted", ru: "искушённый"},
  {en: "pride", ru: "гордость"},
  {en: "clever", ru: "умный"},
  {en: "cheat", ru: "обманывать"},
  {en: "revealed", ru: "раскрывать"},
  {en: "helpful", ru: "полезный"}
];
